### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by ShoiraTa** [ShoiraTa/recipe_app#11]
- We are group of 2 people
- Link to Kanban board: https://github.com/ShoiraTa/recipe_app/projects/1

**Comment by elyor-doniyorov** [comment]
Hi @ShoiraTa and @karelvanoordt👋😀, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ] Great job implementing the Kanban Board successfully! However, you still need to implement 2 changes to make your Kanban Board 💯  perfect. They are 👇 
1. Please add the `In Review` column to your Kanban Board;
2. Please make sure you don't have significantly (difference >= 5 points) more or less points than others. Because right now the difference is 5 points. Kindly try to decrease the difference.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by dasileker** [comment]
### **Hi @ShoiraTa ,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
